name: .NET 10 Preview CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 10 Preview
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'preview'

      - name: Restore dependencies
        run: dotnet restore MathHelper.sln

      - name: Build solution
        run: dotnet build MathHelper.sln --no-restore --configuration Release

      - name: Run tests & collect coverage
        run: |
          dotnet test MathHelper.Tests/MathHelper.Tests.csproj \
            --no-build \
            --configuration Release \
            --logger "trx;LogFileName=TestResults.trx" \
            --results-directory TestResults \
            --collect:"XPlat Code Coverage"

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: dotnet Tests
          path: TestResults/*.trx
          reporter: dotnet-trx

      - name: Generate Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'TestResults/**/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'
      
      - name: Add Coverage Summary to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: TestResults/*.trx

      - name: Publish Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: Code Coverage
          path: TestResults/**/coverage.cobertura.xml

      - name: Publish Console App
        run: |
          cd MathHelper.Console
          dotnet publish --no-build \
              --configuration Release \
              --output ../published

      - name: Upload Console App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MathHelper.Console
          path: published/**/*
